### ISSUE TITLE
How did you get the hash of Nintondo as 04ffff001d0104084e696e746f6e646f?

### ISSUE THREAD

**Issue by commentors-net** [rnicoll/altcoinj#33]
In class org.libdohj.params.AbstractDogecoinParams.java, method createGenesis, the byte array of string "04ffff001d0104084e696e746f6e646f" is retrieved.
In dogecoin code, it is pszTimestamp, which is Nintodo, while in java during decode, I get Nintodo but prefix with some funny charatcters.
Could you please update me as how did you get "04ffff001d0104084e696e746f6e646f" from Nintondo? 
It would be great because I am trying to extend this feature for my test project as proof of concept of porting c++ crypto to java code.

Thank you.

**Comment by rnicoll** [comment]
So that value is the script input, which includes Nintondo but also some extra parts to make it an input. In Dogecoin Core it's built in the line: https://github.com/dogecoin/dogecoin/blob/master/src/chainparams.cpp#L106

Pretty certain what I actually did was to get the genesis block from the Dogecoin Core RPC interface and pulled out the value it contained, rather than rebuilding it from scratch.
